#!/bin/sh

BUILD_LIBS_DIR=$(cd ${0%/*} && pwd)

export CORE_TOP=${BUILD_LIBS_DIR%/*}
#cd $CORE_TOP

AGCC_BIN=$CORE_TOP/support/agcc.pl

TOOLCHAIN=$CORE_TOP/toolchain
PATH=$CORE_TOP/support:$TOOLCHAIN/bin:$PATH

$AGCC_BIN $@
